/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logica.Proceso;
import Logica.Recurso;

/*
 * @author César Salazar y Loredana de Miro
 */
public class InterfazRecursos extends javax.swing.JFrame 
{

    private Proceso Vector_Procesos[]; 
    private Recurso Vector_Recursos[];
    private int id_recurso = 0;
    

    public InterfazRecursos(Recurso[] vecRecursos, Proceso[] vecProcesos) 
    {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        ListaNuevosRecursos.removeAllItems();
        this.Vector_Procesos = vecProcesos;
        this.Vector_Recursos = vecRecursos;
    }

    private InterfazRecursos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NombreRecurso = new javax.swing.JTextField();
        AgregarRecurso = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CantidadRecurso = new javax.swing.JTextField();
        Iniciar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ListaNuevosRecursos = new javax.swing.JComboBox();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Harvest", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Recursos del Sistema");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        getContentPane().add(NombreRecurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 170, -1));

        AgregarRecurso.setBackground(new java.awt.Color(0, 51, 204));
        AgregarRecurso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AgregarRecurso.setForeground(new java.awt.Color(255, 255, 255));
        AgregarRecurso.setText("Agregar");
        AgregarRecurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarRecursoMouseClicked(evt);
            }
        });
        getContentPane().add(AgregarRecurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        CantidadRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadRecursoActionPerformed(evt);
            }
        });
        getContentPane().add(CantidadRecurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 170, -1));

        Iniciar.setBackground(new java.awt.Color(0, 51, 204));
        Iniciar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Iniciar.setForeground(new java.awt.Color(255, 255, 255));
        Iniciar.setText("Iniciar");
        Iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarMouseClicked(evt);
            }
        });
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });
        getContentPane().add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lista de Recursos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        getContentPane().add(ListaNuevosRecursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 310, -1));

        exit.setBackground(new java.awt.Color(0, 51, 204));
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wallpapers-musica-fondos-de-pantalla-plan-alta-tecnolog-a-electr-nica-neon-un-1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-660, -160, 1060, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarRecursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarRecursoMouseClicked
        // TODO add your handling code here:
        if(!"".equals(NombreRecurso.getText()) && !"".equals(CantidadRecurso.getText()))
        {
            Recurso recurso = new Recurso ();
            recurso.setNombre(NombreRecurso.getText());
            recurso.setCantidad(Integer.parseInt(CantidadRecurso.getText()));
            ListaNuevosRecursos.addItem(NombreRecurso.getText());
            Vector_Recursos [id_recurso] = recurso;
            id_recurso++;
            NombreRecurso.setText("");
            CantidadRecurso.setText("");
        }

    }//GEN-LAST:event_AgregarRecursoMouseClicked

    private void IniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarMouseClicked
        // TODO add your handling code here:
        InterfazSimulador main = new InterfazSimulador(Vector_Procesos,Vector_Recursos);
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_IniciarMouseClicked

    private void CantidadRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadRecursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadRecursoActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRecursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRecursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRecursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRecursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new InterfazRecursos().setVisible(true);
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarRecurso;
    private javax.swing.JTextField CantidadRecurso;
    private javax.swing.JButton Iniciar;
    private javax.swing.JComboBox ListaNuevosRecursos;
    private javax.swing.JTextField NombreRecurso;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
