package GUI;

import Logica.Proceso;
import Logica.Recurso;
import Logica.Prediccion;
import Logica.Deteccion;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class InterfazSimulador extends javax.swing.JFrame 
{

    //Variables:
    DefaultListModel modelo;
    private int id_proceso=0;
    private int MaxCantRecursos [] = new int[10];
    private Proceso Vector_Proceso[];
    private Recurso Vector_Recurso[];
    private int [] cant_max_recursos;
    private int id_recurso;
    private int Cont_ProcesosCreados = 0;
    private int Solicitudes = 0;
    public Prediccion Prediccion;
    public Deteccion Deteccion;
    private Object Consola_P;
    
    //Constructor:
    public InterfazSimulador(Proceso[] Vector_Proceso, Recurso[] Vector_Recurso, int[] cant_max_recursos) 
    {
        initComponents();
        this.getContentPane().setBackground(Color.lightGray);
        setLocationRelativeTo(null);
        setResizable(false);
        this.Vector_Proceso = Vector_Proceso;
        this.Vector_Recurso = Vector_Recurso;
        this.cant_max_recursos = cant_max_recursos;
        this.Prediccion = new Prediccion (Vector_Recurso,ConsolePrediccion);
        this.Deteccion = new Deteccion (Vector_Recurso, ConsoleDeteccion);
        modelo = new DefaultListModel();
        ListaRecursosAsignados.setModel(modelo);
        llenar_ComboBoxRecursos();
        llenar_ComboBoxRecursosDelProceso();
        inicializar_MaxCantRecursosxProcesos();
    }
    
    //Constructor vacío:
    private InterfazSimulador() 
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    //Inicializa el vector con la cantidad máx. de recursos permitida por proceso:
    private void inicializar_MaxCantRecursosxProcesos () 
    {
        for (int i = 0; i < MaxCantRecursos.length ; i++) 
        {
            MaxCantRecursos[i]=0;
        } 
    }
    
    //Llena la ComboBox con los recursos asignados al proceso 'x':
    private void llenar_ComboBoxRecursosDelProceso()
    {
        for (int i = 0; i < Vector_Recurso.length; i++) 
        {
            if (Vector_Recurso[i]!= null) 
            {
                RecursoDelProceso.addItem(Vector_Recurso[i].getNombre());
            }     
        }
    }
    
    //Llena la ComboBox con los recursos creados inicialmente:
    private void llenar_ComboBoxRecursos()
    {
        for (int i = 0; i < Vector_Recurso.length; i++) 
        {
            if (Vector_Recurso[i]!= null) 
            {
                ComboBoxTipoRecursos.addItem(Vector_Recurso[i].getNombre());
            }  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ListaProcesos = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NombreRecurso2 = new javax.swing.JTextField();
        Solicitar = new javax.swing.JButton();
        RecursoDelProceso = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NombreProceso = new javax.swing.JTextField();
        ComboBoxTipoRecursos = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CMaxProceso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaRecursosAsignados = new javax.swing.JList();
        CrearProceso = new javax.swing.JButton();
        AgregarAProceso = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        DprocesosCreados = new javax.swing.JLabel();
        DprocesosSistema = new javax.swing.JLabel();
        Dsolicitudes = new javax.swing.JLabel();
        DprocesosBloq = new javax.swing.JLabel();
        DtotalBloq = new javax.swing.JLabel();
        DtotalElim = new javax.swing.JLabel();
        Dtiempo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ConsoleDeteccion = new javax.swing.JTextArea();
        limpiarDeteccion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        PprocesosCreados = new javax.swing.JLabel();
        PprocesosSistema = new javax.swing.JLabel();
        Psolicitudes = new javax.swing.JLabel();
        PprocesosBloq = new javax.swing.JLabel();
        PtotalBloq = new javax.swing.JLabel();
        PtotalElim = new javax.swing.JLabel();
        Ptiempo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConsolePrediccion = new javax.swing.JTextArea();
        limpiarPrediccion = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel6.setFont(new java.awt.Font("Harvest", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Realizar Solicitud");

        jLabel7.setText("Selecciona el Proceso");

        ListaProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaProcesosActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Recurso");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Cantidad");

        NombreRecurso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreRecurso2ActionPerformed(evt);
            }
        });

        Solicitar.setBackground(new java.awt.Color(0, 51, 153));
        Solicitar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Solicitar.setForeground(new java.awt.Color(255, 255, 255));
        Solicitar.setText("Solicitar");
        Solicitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SolicitarMouseClicked(evt);
            }
        });
        Solicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(ListaProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Solicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RecursoDelProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreRecurso2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel6)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListaProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RecursoDelProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NombreRecurso2)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Solicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 440, 200));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Harvest", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Introduccir Proceso");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 0, -1, 38));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre del Proceso");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 44, -1, 31));

        NombreProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreProcesoActionPerformed(evt);
            }
        });
        jPanel1.add(NombreProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 51, 84, -1));

        ComboBoxTipoRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTipoRecursosActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBoxTipoRecursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 217, -1));

        jLabel4.setText("Selecciona el tipo de Recurso");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, -1, 21));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Cantidad Máxima");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 21));

        CMaxProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMaxProcesoActionPerformed(evt);
            }
        });
        jPanel1.add(CMaxProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 76, -1));

        jScrollPane1.setViewportView(ListaRecursosAsignados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 186, 120));

        CrearProceso.setBackground(new java.awt.Color(0, 51, 153));
        CrearProceso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CrearProceso.setForeground(new java.awt.Color(255, 255, 255));
        CrearProceso.setText("Crear");
        CrearProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearProcesoActionPerformed(evt);
            }
        });
        jPanel1.add(CrearProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        AgregarAProceso.setBackground(new java.awt.Color(0, 51, 153));
        AgregarAProceso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AgregarAProceso.setForeground(new java.awt.Color(255, 255, 255));
        AgregarAProceso.setText("Agregar");
        AgregarAProceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarAProcesoMouseClicked(evt);
            }
        });
        AgregarAProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAProcesoActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarAProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 440, 200));

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Harvest", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 153));
        jLabel17.setText("Método de Detección");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 0, 188, 38));

        jLabel19.setText("Nro. de Procesos creados");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 44, 171, 21));

        jLabel26.setText("Nro. de Solicitudes realizadas");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 98, 171, 21));

        jLabel27.setText("Nro. de Procesos en Sistema");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 71, 171, 21));

        jLabel28.setText("Total de Procesos Bloqueados");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 152, 171, 21));

        jLabel29.setText("Nro. de Procesos Bloqueados");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 125, 171, 21));

        jLabel30.setText("Total de Procesos Eliminados");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 179, 171, 21));

        jLabel31.setText("Tiempo");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 206, 161, 21));

        DprocesosCreados.setText("0");
        jPanel4.add(DprocesosCreados, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 44, 30, 21));

        DprocesosSistema.setText("0");
        jPanel4.add(DprocesosSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 71, 30, 21));

        Dsolicitudes.setText("0");
        jPanel4.add(Dsolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 98, 30, 21));

        DprocesosBloq.setText("0");
        jPanel4.add(DprocesosBloq, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 125, 30, 21));

        DtotalBloq.setText("0");
        jPanel4.add(DtotalBloq, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 152, 30, 21));

        DtotalElim.setText("0");
        jPanel4.add(DtotalElim, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 179, 30, 21));

        Dtiempo.setText("0");
        jPanel4.add(Dtiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 206, 30, 21));

        ConsoleDeteccion.setEditable(false);
        ConsoleDeteccion.setColumns(20);
        ConsoleDeteccion.setRows(5);
        jScrollPane3.setViewportView(ConsoleDeteccion);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 44, 160, 160));

        limpiarDeteccion.setBackground(new java.awt.Color(0, 51, 153));
        limpiarDeteccion.setForeground(new java.awt.Color(255, 255, 255));
        limpiarDeteccion.setText("Limpiar");
        limpiarDeteccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarDeteccionActionPerformed(evt);
            }
        });
        jPanel4.add(limpiarDeteccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 440, 260));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setForeground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Harvest", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText("Método de Predicción");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 0, 193, 38));

        jLabel11.setText("Nro. de Procesos creados");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 44, 171, 21));

        jLabel12.setText("Nro. de Solicitudes realizadas");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 98, 171, 21));

        jLabel13.setText("Nro. de Procesos en Sistema");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 71, 171, 21));

        jLabel14.setText("Total de Procesos Bloqueados");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 152, 171, 21));

        jLabel15.setText("Nro. de Procesos Bloqueados");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 125, 171, 21));

        jLabel16.setText("Total de Procesos Finalizados");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 179, 171, 21));

        jLabel18.setText("Tiempo");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 206, 161, 21));

        PprocesosCreados.setText("0");
        jPanel3.add(PprocesosCreados, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 44, 30, 21));

        PprocesosSistema.setText("0");
        jPanel3.add(PprocesosSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 71, 30, 21));

        Psolicitudes.setText("0");
        jPanel3.add(Psolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 98, 30, 21));

        PprocesosBloq.setText("0");
        jPanel3.add(PprocesosBloq, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 125, 30, 21));

        PtotalBloq.setText("0");
        jPanel3.add(PtotalBloq, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 152, 30, 21));

        PtotalElim.setText("0");
        jPanel3.add(PtotalElim, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 179, 30, 21));

        Ptiempo.setText("0");
        jPanel3.add(Ptiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 206, 30, 21));

        ConsolePrediccion.setEditable(false);
        ConsolePrediccion.setColumns(20);
        ConsolePrediccion.setRows(5);
        jScrollPane2.setViewportView(ConsolePrediccion);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 44, 160, 160));

        limpiarPrediccion.setBackground(new java.awt.Color(0, 51, 153));
        limpiarPrediccion.setForeground(new java.awt.Color(255, 255, 255));
        limpiarPrediccion.setText("Limpiar");
        limpiarPrediccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarPrediccionActionPerformed(evt);
            }
        });
        jPanel3.add(limpiarPrediccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 440, 260));

        jLabel20.setFont(new java.awt.Font("Harvest", 1, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("UNIMET OS");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        exit.setBackground(new java.awt.Color(0, 51, 153));
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wallpapers-musica-fondos-de-pantalla-plan-alta-tecnolog-a-electr-nica-neon-un-1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CMaxProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMaxProcesoActionPerformed

    }//GEN-LAST:event_CMaxProcesoActionPerformed

    private void CrearProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearProcesoActionPerformed

  
        if (!"".equals(NombreProceso.getText())&& id_proceso<10 && !modelo.isEmpty())
        {
            int AuxMaxCantRecursosPerProcess[] = new int [10];

            for (int i = 0; i < AuxMaxCantRecursosPerProcess.length ; i++) 
            {
                AuxMaxCantRecursosPerProcess[i]=MaxCantRecursos[i];
            }

            Proceso p = new Proceso (NombreProceso.getText(), id_proceso, AuxMaxCantRecursosPerProcess);
            Vector_Proceso [id_proceso] = p;

            Prediccion.Insertar_Procesos(Vector_Proceso[id_proceso].getCant_max(),Vector_Proceso[id_proceso].getId_proceso() );
            Deteccion.Insertar_Procesos(Vector_Proceso[id_proceso].getCant_max(),Vector_Proceso[id_proceso].getId_proceso());

            id_proceso++;
            ListaProcesos.addItem(p.getNombre_proceso());
            modelo.removeAllElements();
            NombreProceso.setText("");                
            
            for (int i = 0; i < MaxCantRecursos.length ; i++) 
            {
                MaxCantRecursos[i]=0;
            }
            Cont_ProcesosCreados++;
            PprocesosCreados.setText(Integer.toString(Cont_ProcesosCreados));
            DprocesosCreados.setText(Integer.toString(Cont_ProcesosCreados));

        }
        else if(id_proceso>=10)
        { 
            JOptionPane.showMessageDialog(null, "ERROR. Se ha alcanzado el número máximo de procesos que pueden ser creados.");
            modelo.removeAllElements();
        }
        else if("".equals(NombreProceso.getText()))
        {
            JOptionPane.showMessageDialog(null, "ERROR. Escriba el nombre del proceso.");
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "ERROR.  No se puede crear proceso si no se han añadido recursos.");
        }

    }//GEN-LAST:event_CrearProcesoActionPerformed

    private void AgregarAProcesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarAProcesoMouseClicked

    }//GEN-LAST:event_AgregarAProcesoMouseClicked

    private void AgregarAProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAProcesoActionPerformed

        id_recurso = ComboBoxTipoRecursos.getSelectedIndex();
        String Tipo_Recurso = ComboBoxTipoRecursos.getSelectedItem().toString();

        if (Tipo_Recurso!=null && !"".equals(CMaxProceso.getText()) && !"".equals(NombreProceso.getText()) && Integer.parseInt(CMaxProceso.getText())<= cant_max_recursos[id_recurso] &&  Integer.parseInt(CMaxProceso.getText())>0)
        {
            modelo.addElement(" Recurso: "+Tipo_Recurso+"        "+"  Cantidad: "+CMaxProceso.getText());
            MaxCantRecursos[id_recurso]=Integer.parseInt(CMaxProceso.getText());
        }
        else if("".equals(NombreProceso.getText()))
        {
            JOptionPane.showMessageDialog(null, "ERROR. Inserte un nombre al proceso a agregar recursos.");            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "ERROR. Puede que algún parámetro introducido sea inválido.");
        }

        CMaxProceso.setText("");
    }//GEN-LAST:event_AgregarAProcesoActionPerformed

    private void ListaProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaProcesosActionPerformed

    }//GEN-LAST:event_ListaProcesosActionPerformed

    private void SolicitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SolicitarMouseClicked
    
    }//GEN-LAST:event_SolicitarMouseClicked

    private void SolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitarActionPerformed
            if (!"".equals(NombreRecurso2.getText()))
    {
        if (Vector_Proceso[ListaProcesos.getSelectedIndex()].getCant_maxPOSICION(RecursoDelProceso.getSelectedIndex())!=0) 
        {
            int CantidadSolicitada = Integer.parseInt(NombreRecurso2.getText());
            
            if ( CantidadSolicitada  <= Vector_Proceso[ListaProcesos.getSelectedIndex()].getCant_maxPOSICION(RecursoDelProceso.getSelectedIndex()) && CantidadSolicitada>0) 
            {
                int AuxSolicitud [] = new int [10];
                
                for (int i = 0; i < AuxSolicitud.length ; i++) 
                {
                    AuxSolicitud [i] = 0;
                }
                    AuxSolicitud [RecursoDelProceso.getSelectedIndex()] = CantidadSolicitada;
                    Prediccion.Ejecutar(Vector_Proceso[ListaProcesos.getSelectedIndex()].getId_proceso(), AuxSolicitud);
                    Deteccion.Ejecutar(Vector_Proceso[ListaProcesos.getSelectedIndex()].getId_proceso(), AuxSolicitud);
                }
            else 
            {
                JOptionPane.showMessageDialog(null, "ERROR. ¡Recurso solicitado para el proceso inválido! Puede que haya sobrepasado el máximo especificado o haya puesto un número negativo.");
            }
            
            }
            else
            {
                JOptionPane.showMessageDialog(null, "ERROR. Este recurso no es usado por el proceso: "+Vector_Proceso[ListaProcesos.getSelectedIndex()].getNombre_proceso());
            }

            Solicitudes++;
            Dsolicitudes.setText(Integer.toString(Solicitudes));
            Psolicitudes.setText(Integer.toString(Solicitudes));
            PprocesosBloq.setText(Integer.toString(Prediccion.getPro_bloqueados()));
            PtotalBloq.setText(Integer.toString(Prediccion.getPro_bloq_Total()));
            PtotalElim.setText(Integer.toString(Prediccion.getPro_finalizados()));
            Ptiempo.setText(Long.toString(Prediccion.getTiempo()));

            Dtiempo.setText(Long.toString(Deteccion.getTiempo()));
            DprocesosBloq.setText(Integer.toString(Deteccion.getBloqueo_actual()));
            DtotalBloq.setText(Integer.toString(Deteccion.getPro_bloq_Total()));
            DtotalElim.setText(Integer.toString(Deteccion.getPro_eliminados()));
            NombreRecurso2.setText("");

            PprocesosSistema.setText(Integer.toString(Prediccion.getProcesos_sistema()));
            DprocesosSistema.setText(Integer.toString(Deteccion.getProcesos_sistema()));

    }
    }//GEN-LAST:event_SolicitarActionPerformed

    private void NombreRecurso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreRecurso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreRecurso2ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
            System.exit(0);      
    }//GEN-LAST:event_exitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            modelo.removeAllElements();     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboBoxTipoRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTipoRecursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxTipoRecursosActionPerformed

    private void NombreProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreProcesoActionPerformed

    private void limpiarPrediccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarPrediccionActionPerformed
        ConsolePrediccion.setText("");

    }//GEN-LAST:event_limpiarPrediccionActionPerformed

    private void limpiarDeteccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarDeteccionActionPerformed
        ConsoleDeteccion.setText("");

    }//GEN-LAST:event_limpiarDeteccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    //Quitar los comentarios
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazSimulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazSimulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazSimulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazSimulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //Quitar los comentarios
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new InterfazSimulador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarAProceso;
    private javax.swing.JTextField CMaxProceso;
    private javax.swing.JComboBox ComboBoxTipoRecursos;
    private javax.swing.JTextArea ConsoleDeteccion;
    private javax.swing.JTextArea ConsolePrediccion;
    private javax.swing.JButton CrearProceso;
    private javax.swing.JLabel DprocesosBloq;
    private javax.swing.JLabel DprocesosCreados;
    private javax.swing.JLabel DprocesosSistema;
    private javax.swing.JLabel Dsolicitudes;
    private javax.swing.JLabel Dtiempo;
    private javax.swing.JLabel DtotalBloq;
    private javax.swing.JLabel DtotalElim;
    private javax.swing.JComboBox ListaProcesos;
    private javax.swing.JList ListaRecursosAsignados;
    private javax.swing.JTextField NombreProceso;
    private javax.swing.JTextField NombreRecurso2;
    private javax.swing.JLabel PprocesosBloq;
    private javax.swing.JLabel PprocesosCreados;
    private javax.swing.JLabel PprocesosSistema;
    private javax.swing.JLabel Psolicitudes;
    private javax.swing.JLabel Ptiempo;
    private javax.swing.JLabel PtotalBloq;
    private javax.swing.JLabel PtotalElim;
    private javax.swing.JComboBox RecursoDelProceso;
    private javax.swing.JButton Solicitar;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton limpiarDeteccion;
    private javax.swing.JButton limpiarPrediccion;
    // End of variables declaration//GEN-END:variables
}
